export const PostActionTypes = {
  POST_LOADING_START: 'POST_LOADING_START',
  POST_LOADING_SUCCESS: 'POST_LOADING_SUCCESS',
  POST_LOADING_FAILURE: 'POST_LOADING_FAILURE',
  COMMENT_LOADING_START: 'COMMENT_LOADING_START',
  COMMENT_LOADING_SUCCESS: 'COMMENT_LOADING_SUCCESS',
  COMMENT_LOADING_FAILURE: 'COMMENT_LOADING_FAILURE',
  ADD_COMMENT_START: 'ADD_COMMENT_START',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
  REPLY_COMMENT_START: 'REPLY_COMMENT_START',
  REPLY_COMMENT_SUCCESS: 'REPLY_COMMENT_SUCCESS',
  REPLY_COMMENT_FAILURE: 'REPLY_COMMENT_FAILURE'
}

export default PostActionTypes
