export const FeedActionTypes = {
  FEED_LOADING_START: 'FEED_LOADING_START',
  FEED_LOADING_SUCCESS: 'FEED_LOADING_SUCCESS',
  FEED_LOADING_FAILURE: 'FEED_LOADING_FAILURE',
  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_SUCCESS: 'ADD_POST_SUCCESS',
  ADD_POST_FAILURE: 'ADD_POST_FAILURE'
}

export default FeedActionTypes
